name: Publish Kraken To pub.dev

on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publishToPubDev:
    runs-on: [self-hosted, flutter_2.5.3]
    steps:
    - uses: actions/checkout@v2
    - name: NPM INSTALL
      run: npm install
    - name: Build bridge binary
      run: npm run build:bridge:all:release
    - name: Publish to dart.dev
      run: cd kraken && flutter pub publish --force
